### ISSUE TITLE
ImportError: cannot import name find_indentation

### ISSUE THREAD

**Issue by mete0r** [spulec/pep8ify#2]
with python2.6, `pep8ify` raises `ImportError` as following:

```
Traceback (most recent call last):
  File "bin/pep8ify", line 14, in <module>
    pep8ify.pep8ify._main()
  File "/home/mete0r/prj/pyhwp/eggs/pep8ify-0.0.5-py2.6.egg/pep8ify/pep8ify.py", line 12, in _main
    sys.exit(main("pep8ify.fixes"))
  File "/usr/lib/python2.6/lib2to3/main.py", line 156, in main
    options.nobackups, not options.no_diffs)
  File "/usr/lib/python2.6/lib2to3/main.py", line 32, in __init__
    super(StdoutRefactoringTool, self).__init__(fixers, options, explicit)
  File "/usr/lib/python2.6/lib2to3/refactor.py", line 606, in __init__
    super(MultiprocessRefactoringTool, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.6/lib2to3/refactor.py", line 200, in __init__
    self.pre_order, self.post_order = self.get_fixers()
  File "/usr/lib/python2.6/lib2to3/refactor.py", line 218, in get_fixers
    mod = __import__(fix_mod_path, {}, {}, ["*"])
  File "/home/mete0r/prj/pyhwp/eggs/pep8ify-0.0.5-py2.6.egg/pep8ify/fixes/fix_blank_lines.py", line 2, in <module>
    from lib2to3.fixer_util import find_indentation
ImportError: cannot import name find_indentation
```

It seems not clear that whether this is a known limitation or  unintended error.

**Comment by spulec** [comment]
It's a known issue, but I've updated the README to make this clear that there is currently only python 2.7 compatibility. This library is heavily reliant upon the lib2to3 standard library which I believe was not very developed back in 2.6. If I get some free time, I'll investigate what it would take to back-port.
